name: "❓ 질문"
description: "프로젝트에 대한 질문이나 도움이 필요할 때 사용합니다."
title: "[질문]"
labels: ["question", "triage"]
assignees:
  - support-team
body:
  - type: markdown
    attributes:
      value: |
        감사합니다! 질문 작성을 도와주셔서 감사합니다. 아래 양식을 작성해 주세요.
  - type: dropdown
    id: position
    attributes:
      label: 질문자 포지션
      description: 질문자의 역할을 선택해 주세요.
      options:
        - 디자이너
        - 백엔드
        - 프론트
        - 퍼블리셔
        - 데브옵스
    validations:
      required: true
  - type: input
    id: question_title
    attributes:
      label: 질문 제목
      description: 질문의 제목을 간략하게 작성해 주세요.
      placeholder: 예) 새로운 기능의 구현 방법은?
    validations:
      required: true
  - type: textarea
    id: question_details
    attributes:
      label: 질문 상세 설명
      description: 질문하고 싶은 내용을 상세히 작성해 주세요.
      placeholder: 예) 프로젝트의 새로운 기능을 추가하려고 하는데, 특정 부분에서 문제가 발생하고 있습니다. 해결 방법을 알고 싶습니다.
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: 추가 정보 (선택 사항)
      description: 질문과 관련된 추가 정보를 제공해 주세요.
      placeholder: 예) 관련된 코드 스니펫이나 에러 로그가 있다면 포함해 주세요.
    validations:
      required: false
