# admin/.github/ISSUE_TEMPLATE/security_vulnerability.yml
name: "🔒 보안 취약점 보고"
description: "프로젝트에서 발견된 보안 취약점을 보고할 때 사용합니다."
title: "[보안 취약점]"
labels: ["security", "triage"]
assignees:
  - security-team
body:
  - type: markdown
    attributes:
      value: |
        감사합니다! 보안 취약점 보고 작성을 도와주셔서 감사합니다. 아래 양식을 작성해 주세요.
  - type: input
    id: vulnerability
    attributes:
      label: 취약점 유형
      description: 발견한 보안 취약점의 유형을 선택해 주세요.
      placeholder: 예) XSS, SQL Injection
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 취약점 설명
      description: 발견한 보안 취약점에 대한 상세한 설명을 작성해 주세요.
      placeholder: 예) 로그인 기능에서 사용자 입력을 적절히 검증하지 않아 XSS 공격 가능
    validations:
      required: true
  - type: input
    id: steps_to_reproduce
    attributes:
      label: 재현 단계
      description: 취약점을 재현할 수 있는 단계들을 순서대로 적어 주세요.
      placeholder: 1. 로그인 페이지 접속 2. ...
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 영향도
      description: 이 취약점이 미치는 영향에 대해 설명해 주세요.
      placeholder: 예) 사용자의 민감한 정보 유출 가능
    validations:
      required: false
  - type: textarea
    id: remediation
    attributes:
      label: 수정 방안
      description: 이 취약점을 수정하기 위한 방안을 제안해 주세요.
      placeholder: 예) 사용자 입력에 대한 철저한 검증 추가
    validations:
      required: false
