# admin/.github/ISSUE_TEMPLATE/task.yml
name: "📝 작업(Task)"
description: "프로젝트 내에서 특정 작업이나 할 일을 추적할 때 사용합니다."
title: "[작업]"
labels: ["task", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        감사합니다! 작업(Task) 작성을 도와주셔서 감사합니다. 아래 양식을 작성해 주세요.
  - type: input
    id: task_title
    attributes:
      label: 작업 제목
      description: 수행할 작업의 제목을 간략히 작성해 주세요.
      placeholder: 예) 사용자 인증 시스템 개선
    validations:
      required: true
  - type: textarea
    id: task_description
    attributes:
      label: 작업 설명
      description: 수행할 작업에 대해 상세히 설명해 주세요.
      placeholder: 예) 현재 사용자 인증 시스템의 보안 강화를 위해 추가적인 검증 절차를 도입합니다.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 단계별 절차
      description: 작업을 완료하기 위한 단계별 절차를 작성해 주세요.
      placeholder: 예) 1. 추가 검증 로직 구현 2. 테스트 케이스 작성 3. 코드 리뷰 요청
    validations:
      required: false
  - type: input
    id: due_date
    attributes:
      label: 마감일 (선택 사항)
      description: 작업의 마감일을 입력해 주세요.
      placeholder: 예) 2024-05-30
    validations:
      required: false
